In [3]:
!pip install pandas pandas-gbq google-cloud-bigquery pyarrow

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.41.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.5.1)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.3)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.3.1)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.74.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.27.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.4.22)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)

Reading CSV files

In [4]:
import pandas as pd

party_df = pd.read_csv("/content/Parties_seat_2021.csv")
results_2021_df = pd.read_csv("/content/Tamil Nadu Assembly Election Results 2021.csv")
results_2026_df = pd.read_csv("/content/tn-results-2026.csv")

In [5]:
party_df.head()

,ALLIANCE_NAME,PARTY_FULL_NAME,PARTY_ABBR,Total_Constituency
0,National Democratic Alliance,All India Anna Dravida Munnetra Kazhagam,AIADMK,179
1,National Democratic Alliance,Pattali Makkal Katchi,PMK,23
2,National Democratic Alliance,Bharatiya Janata Party,BJP,20
3,National Democratic Alliance,Tamil Maanila Congress (Moopanar),TMC(M),6
4,National Democratic Alliance,Perunthalaivar Makkal Katchi,PTMK,1

In [6]:
results_2021_df.head()

,State_Name,Assembly_No,Constituency_No,Year,month,DelimID,Poll_No,Position,Candidate,Sex,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
0,Tamil_Nadu,12,1,2021,5,4,0,1,GOVINDARAJAN T.J,M,...,1.0,False,False,False,10th Pass,Business,NaN,NaN,NaN,State Assembly Election (AE)
1,Tamil_Nadu,12,1,2021,5,4,0,2,PRAKASH M,M,...,0.0,False,False,False,10th Pass,Salaried Work or Employed,Qualified Professional,NaN,NaN,State Assembly Election (AE)
2,Tamil_Nadu,12,1,2021,5,4,0,3,USHA,F,...,0.0,False,False,False,8th Pass,Agriculture,NaN,NaN,NaN,State Assembly Election (AE)
3,Tamil_Nadu,12,1,2021,5,4,0,4,DILLIY K.M,M,...,0.0,False,False,False,8th Pass,Other,NaN,NaN,NaN,State Assembly Election (AE)
4,Tamil_Nadu,12,1,2021,5,4,0,5,None Of The Above,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,State Assembly Election (AE)

In [7]:
results_2026_df.head()

,AC No,AC Name,Sl no,Candidate,Party,EVM Votes,Postal Votes,Total Votes,Vote Share
0,1,GUMMIDIPOONDI,1,T.J.GOVINDARAJAN,Dravida Munnetra Kazhagam,61922,570,62492,26.88
1,1,GUMMIDIPOONDI,2,SUDHAKAR.V,All India Anna Dravida Munnetra Kazhagam,65894,481,66375,28.55
2,1,GUMMIDIPOONDI,3,M.JAGADEESAN,Bahujan Samaj Party,695,2,697,0.30
3,1,GUMMIDIPOONDI,4,"R.SRIDAR. B.L.,",Naam Tamilar Katchi,4707,49,4756,2.05
4,1,GUMMIDIPOONDI,5,SDK SANKAR,Aanaithinthiya Jananayaka Pathukappu Kazhagam,593,6,599,0.26

Data Cleaning

In [8]:
#copying 2021 results to a new df

results_2021_clean = results_2021_df[[
    'Year',
    'Constituency_Name',
    'Candidate',
    'Party',
    'Votes',
    'Vote_Share_Percentage'
]].copy()

In [9]:
#choosing only the required columns

results_2021_clean.columns = [
    'election_year',
    'constituency_name',
    'candidate',
    'party',
    'total_votes',
    'vote_share'
]

In [10]:
#copying 2026 results to a new df

results_2026_clean = results_2026_df[[
    'AC Name',
    'Candidate',
    'Party',
    'Total Votes',
    'Vote Share'
]].copy()

In [11]:
results_2026_clean['election_year'] = 2026

In [12]:
#choosing only the required columns
#Rearranging the columns

results_2026_clean = results_2026_clean[[
    'election_year',
    'AC Name',
    'Candidate',
    'Party',
    'Total Votes',
    'Vote Share'
]]

In [13]:
results_2026_clean.columns = [
    'election_year',
    'constituency_name',
    'candidate',
    'party',
    'total_votes',
    'vote_share'
]

In [14]:
#Combining 2021 and 2026 results for Dashboard purpose

combined_results = pd.concat(
    [results_2021_clean, results_2026_clean],
    ignore_index=True
)

In [15]:
combined_results.head()

,election_year,constituency_name,candidate,party,total_votes,vote_share
0,2021,GUMMIDIPUNDI,GOVINDARAJAN T.J,DMK,126452,56.94
1,2021,GUMMIDIPUNDI,PRAKASH M,PMK,75514,34.00
2,2021,GUMMIDIPUNDI,USHA,NTK,11701,5.27
3,2021,GUMMIDIPUNDI,DILLIY K.M,DMDK,2576,1.16
4,2021,GUMMIDIPUNDI,None Of The Above,NOTA,1783,0.80

In [16]:
combined_results.tail()

,election_year,constituency_name,candidate,party,total_votes,vote_share
8484,2026,KILLIYOOR,AJAI (ALIAS) NAGARAJAN,Independent,241,0.14
8485,2026,KILLIYOOR,BERRILA. L,Independent,197,0.11
8486,2026,KILLIYOOR,BABY RAJ. P,Independent,162,0.09
8487,2026,KILLIYOOR,JUSTIN. M,Independent,189,0.11
8488,2026,KILLIYOOR,NOTA,None of the Above,502,0.28

In [17]:
combined_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8489 entries, 0 to 8488
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   election_year      8489 non-null   int64
 1   constituency_name  8489 non-null   object
 2   candidate          8489 non-null   object
 3   party              8489 non-null   object
 4   total_votes        8489 non-null   int64
 5   vote_share         8489 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 398.1+ KB

In [18]:
#removing missing values

combined_results = combined_results.dropna()

In [19]:
#droping duplicates

combined_results = combined_results.drop_duplicates()

In [20]:
from google.colab import auth
auth.authenticate_user()

In [21]:
#connecting with big query

combined_results.to_gbq(
    destination_table='tn_election.election_results',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/3942191734.py:3: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  combined_results.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 9425.40it/s]

In [22]:
party_df.to_gbq(
    destination_table='tn_election.party_summary',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/385260649.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  party_df.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 10922.67it/s]

In [23]:
district_mapping = results_2021_df[[
    'Constituency_Name',
    'District_Name'
]].drop_duplicates()

In [24]:
district_mapping.columns = [
    'constituency_name',
    'district_name'
]

In [25]:
district_mapping['constituency_name'] = (
    district_mapping['constituency_name']
    .str.strip()
    .str.lower()
)

In [26]:
combined_results = combined_results.merge(
    district_mapping,
    on='constituency_name',
    how='left'
)

In [27]:
combined_results.head()

,election_year,constituency_name,candidate,party,total_votes,vote_share,district_name
0,2021,GUMMIDIPUNDI,GOVINDARAJAN T.J,DMK,126452,56.94,NaN
1,2021,GUMMIDIPUNDI,PRAKASH M,PMK,75514,34.00,NaN
2,2021,GUMMIDIPUNDI,USHA,NTK,11701,5.27,NaN
3,2021,GUMMIDIPUNDI,DILLIY K.M,DMDK,2576,1.16,NaN
4,2021,GUMMIDIPUNDI,None Of The Above,NOTA,1783,0.80,NaN

In [28]:
combined_results['district_name'].isnull().sum()

np.int64(8489)

In [29]:
combined_results['constituency_name'] = (
    combined_results['constituency_name']
    .str.strip()
    .str.lower()
)

In [30]:
combined_results = combined_results.drop(columns=['district_name'], errors='ignore')

combined_results = combined_results.merge(
    district_mapping,
    on='constituency_name',
    how='left'
)

In [31]:
combined_results.head()

,election_year,constituency_name,candidate,party,total_votes,vote_share,district_name
0,2021,gummidipundi,GOVINDARAJAN T.J,DMK,126452,56.94,TIRUVALLUR
1,2021,gummidipundi,PRAKASH M,PMK,75514,34.00,TIRUVALLUR
2,2021,gummidipundi,USHA,NTK,11701,5.27,TIRUVALLUR
3,2021,gummidipundi,DILLIY K.M,DMDK,2576,1.16,TIRUVALLUR
4,2021,gummidipundi,None Of The Above,NOTA,1783,0.80,TIRUVALLUR

In [32]:
combined_results['district_name'].isnull().sum()

np.int64(638)

In [33]:
missing_constituencies = combined_results[
    combined_results['district_name'].isnull()
]['constituency_name'].unique()

missing_constituencies

array(['gummidipoondi', 'dr.radhakrishnan nagar', 'thiyagarayanagar',
       'madurantakam', 'arakkonam', 'sholingur', 'gudiyattam',
       'vaniyambadi', 'palacodu', 'pappireddipatti', 'viluppuram',
       'ulundurpettai', 'rishivandiyam', 'edappadi', 'senthamangalam',
       'tiruchengodu', 'modakkurichi', 'mettuppalayam',
       'coimbatore (north)', 'coimbatore (south)', 'udumalaipettai',
       'nilakkottai', 'tiruchirappalli (west)', 'tiruchirappalli (east)',
       'thiruverumbur', 'sirkazhi', 'thiruthuraipoondi',
       'thiruvidaimarudur', 'orathanadu', 'aranthangi', 'aruppukkottai',
       'mudhukulathur', 'palayamkottai', 'colachal'], dtype=object)

In [34]:
replacement_dict = {
    'coimbatore (north)': 'coimbatore north',
    'coimbatore (south)': 'coimbatore south',
    'tiruchirappalli (west)': 'tiruchirappalli west',
    'tiruchirappalli (east)': 'tiruchirappalli east',
    'dr.radhakrishnan nagar': 'dr radhakrishnan nagar',
    'thiyagarayanagar': 'thyagaraya nagar',
    'madurantakam': 'maduranthakam',
    'viluppuram': 'villupuram',
    'thiruverumbur': 'thiruverumbur',
    'thiruthuraipoondi': 'thiruthuraipundi',
    'thiruvidaimarudur': 'thiruvidaimaruthur',
    'mudhukulathur': 'mudukulathur',
    'colachal': 'colachel'
}

In [35]:
combined_results['constituency_name'] = combined_results[
    'constituency_name'
].replace(replacement_dict)

In [36]:
combined_results = combined_results.drop(
    columns=['district_name'],
    errors='ignore'
)

combined_results = combined_results.merge(
    district_mapping,
    on='constituency_name',
    how='left'
)

In [37]:
combined_results['district_name'].isnull().sum()

np.int64(497)

In [38]:
combined_results['district_geo'] = (
    combined_results['district_name'] + ', Tamil Nadu, India'
)

In [39]:
combined_results.to_gbq(
    destination_table='tn_election.election_results',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/3097569031.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  combined_results.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 10230.01it/s]

In [40]:
combined_results[
    combined_results['election_year'] == 2021
]['total_votes'].sum()

np.int64(47426580)

In [41]:
combined_results.shape

(8741, 8)

In [42]:
combined_results.drop_duplicates().shape

(8573, 8)

In [43]:
combined_results.to_gbq(
    destination_table='tn_election.election_results',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/3097569031.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  combined_results.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 9098.27it/s]

In [44]:
combined_results = combined_results.drop_duplicates()

In [45]:
combined_results[
    combined_results['election_year'] == 2021
].duplicated(
    subset=['constituency_name', 'candidate', 'party', 'total_votes']
).sum()

np.int64(43)

In [46]:
combined_results = combined_results.drop_duplicates(
    subset=[
        'election_year',
        'constituency_name',
        'candidate',
        'party',
        'total_votes'
    ]
)

In [47]:
district_mapping['constituency_name'].duplicated().sum()

np.int64(1)

In [48]:
district_mapping = district_mapping.drop_duplicates(
    subset=['constituency_name']
)

In [49]:
combined_results = combined_results.drop(
    columns=['district_name'],
    errors='ignore'
)

In [50]:
combined_results = combined_results.merge(
    district_mapping,
    on='constituency_name',
    how='left'
)

In [51]:
combined_results = combined_results.drop_duplicates()

In [52]:
combined_results[
    combined_results['election_year'] == 2021
]['total_votes'].sum()

np.int64(46236492)

In [53]:
combined_results.to_gbq(
    destination_table='tn_election.election_results',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/3097569031.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  combined_results.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 11586.48it/s]

In [54]:
combined_results.shape

(8489, 8)

In [55]:
results_2021_clean["party"].nunique()

109

In [56]:
results_2021_clean.groupby('party')['vote_share'].mean()

party
ADMK                                                    40.226073
AIMIM                                                    0.530000
AISMK                                                    1.336667
AITC                                                     0.280000
AMMK                                                     3.342061
                                                          ...
Universal Brotherhood Movement                           0.050000
VCK                                                     42.581667
Valamaana  Tamizhagam   Katchi                           0.180000
Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi     0.116452
Vidial Valarchi Perani                                   0.060000
Name: vote_share, Length: 109, dtype: float64

In [58]:
party_df['Total_Constituency'].sum()

np.int64(1397)

In [60]:
party_summary = party_df.groupby(
    'PARTY_ABBR'
)['Total_Constituency'].max().reset_index()

In [62]:
party_summary['Total_Constituency'].sum()

np.int64(1396)

In [63]:
winners = combined_results.loc[
    combined_results.groupby(
        ['election_year', 'constituency_name']
    )['total_votes'].idxmax()
]

In [64]:
seat_share = winners.groupby(
    ['election_year', 'party']
).size().reset_index(name='Seats_Won')

In [65]:
seat_share[
    seat_share['election_year'] == 2021
]['Seats_Won'].sum()

np.int64(233)

In [66]:
seat_share.to_gbq(
    destination_table='tn_election.seat_share',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/982998653.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  seat_share.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 11915.64it/s]

In [67]:
winners = combined_results.loc[
    combined_results.groupby(
        ['election_year', 'constituency_name']
    )['total_votes'].idxmax()
]

seat_share = winners.groupby(
    ['election_year', 'party']
).size().reset_index(name='Seats_Won')

In [68]:
seat_share.to_gbq(
    destination_table='tn_election.seat_share',
    project_id='perfect-trilogy-495613-v4',
    if_exists='replace'
)

/tmp/ipykernel_1808/982998653.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  seat_share.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 8886.24it/s]